# Development overrides for faster builds
# Use with: bundle exec jekyll serve --config _config.yml,_config_dev.yml --incremental --livereload

# Disable CSS/HTML minification  
jekyll-minifier:
  enabled: false

# Imagemagick already disabled in main config, but making sure
imagemagick:
  enabled: false

# disable blog lsi
lsi: false # produce an index for related posts

# Remove terser from plugins list to disable JS minification
plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  # - jekyll-terser  # DISABLED for dev
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

  # al-folio plugins
  - al_folio_core
  - al_icons
  - al_folio_cv
  - al_folio_distill
  - al_folio_upgrade
  - al_folio_bootstrap_compat
  - al_cookie
  - al_analytics
  - al_citations
  - al_ext_posts
  - al_img_tools
  - al_search
  - al_charts
  - al_math
  - al_comments
  - al_newsletter